### ISSUE TITLE
getting 301

### ISSUE THREAD

**Issue by adrianpraja** [andris9/public-address#1]
Hi Andris,

Im trying your package on an ec2 server 
```
	publicAddress(function(err, data) {
		console.log("resolving hostname", err, data)
	})
```
the result 

```
	resolving hostname [Error: Invalid response code 301] undefined
```

it seems to me that they are redirecting to https,  then to a login page to Cozy with invalid SSL

Just signaling you as they may be out of service :)

**Comment by andris9** [comment]
You're right, the original remote service does not work anymore. I replaced it with ipfy.org and published the update as version 0.1.2, so upgrading the module should make it work again.
